== Your Git History Is A Mess

One solution : Interactif Rebase.

```
git rebase -i HEAD~<NUMBER OF COMMITS YOU WANT TO REWORK>
```

Number of commits between two branches :

```
git log --oneline <CURRENT BRANCH> ^<BRANCH TO COMPARE WITH> | wc -l
```

=== Rebase Compared To A Branch

```
git rebase <THE BRANCH YOU WANT TO REBASE TO>
```

=== Rewrite Old Commit Messages

```
git rebase -i HEAD~<NUMBER OF COMMITS YOU WANT TO REWORK>
```

Mark the commits you want to rewrite with *reword* instead of *pick*.

=== Condense Commits

Mark the commits you want to fuse into other commits with *squash* instead of *pick*.

=== You Are Out Of Sync With Work Done By Others And Don't Want To Manage Conflicts

```
git checkout <YOUR BRANCH>
git reset origin/<YOUR BRANCH> --hard
```

*BEWARE :* Your recent work on this branch will be lost!

=== Your Local Branch Is More Up To Date Than The Remote

```
git push --force
```

*BEWARE :* It is better to do this only on *your* feature branch, rather than a shared branch like *develop* or, worse, *main* !

=== Squash The Last Commits

```
git reset HEAD~<NUMBER OF COMMITS>
```

=== Delete A Branch

Locally :
```
git branch -d <LOCAL BRANCH NAME>
```

Remotely :
```
git push origin --delete <REMOTE BRANCH NAME>
```

Locally and remotely :
```
git branch -d <LOCAL BRANCH NAME> && git push origin --delete <REMOTE BRANCH NAME>
```

=== Rename A Branch

Locally :
```
git branch -m <OLD NAME> <NEW NAME>
```

Remotely :
```
git branch -m <OLD NAME> <NEW NAME>
git push origin --delete <OLD NAME>
git push origin -u <NEW NAME>
```

=== Change The Author Of The Last Commit

```
git commit ---amend --author="Author Name email@address.com"
```

